all_date<-read.csv('household_power_consumption.txt',sep=';')
specify_date<-tail(head(all_date,69516),2880)
date_time<-paste(specify_date$Date,specify_date$Time)
date_time<-strptime(date_time,'%d/%m/%Y %H:%M:%S')
Global_active_power<-as.numeric(as.character(specify_date$Global_active_power))
Global_reactive_power<-as.numeric(as.character(specify_date$Global_reactive_power))
Voltage<-as.numeric(as.character(specify_date$Voltage))
Sub_metering_1<-as.numeric(as.character(specify_date$Sub_metering_1))
Sub_metering_2<-as.numeric(as.character(specify_date$Sub_metering_2))
Sub_metering_3<-as.numeric(as.character(specify_date$Sub_metering_3))
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))
plot(date_time,Global_active_power,type='l',ylab='Global Active Power')
plot(date_time,Voltage,type='l',ylab='Voltage')
plot(date_time,Sub_metering_1,type='l',ylab = 'Energy sub metering')
lines(date_time,Sub_metering_2,col='red')
lines(date_time,Sub_metering_3,col='blue')
legend("topright",c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),col=c('black','red','blue'),lty=c(1,1),cex=0.4)
plot(date_time,Global_reactive_power,type='l',ylab='Global Reactive Power')
